use muquiventas2018;
-- MySQL Script generated by MySQL Workbench
-- Tue Jan  2 17:40:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, 
FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema muquiventas2018
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema muquiventas2018
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `muquiventas2018` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema muquiventas2018
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema muquiventas2018
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `muquiventas2018` DEFAULT CHARACTER SET latin1 ;
USE `muquiventas2018` ;

-- -----------------------------------------------------
-- Table `muquiventas2018`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muquiventas2018`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `limite` INT(11) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muquiventas2018`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muquiventas2018`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nivel` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `muquiventas2018`.`tventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muquiventas2018`.`tventa` (
  `idVenta` INT(11) NOT NULL AUTO_INCREMENT,
  `precioVentaTotal` DECIMAL(18,2) NOT NULL,
  `fechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_TVenta_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_TVenta_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `muquiventas2018`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11902
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `muquiventas2018`.`formaDePago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muquiventas2018`.`formaDePago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `tventa_idVenta` INT(11) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `cantidad` DECIMAL(18,2) NULL,
  `referencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fk_formaDePago_tventa_idx` (`tventa_idVenta` ASC),
  CONSTRAINT `fk_formaDePago_tventa`
    FOREIGN KEY (`tventa_idVenta`)
    REFERENCES `muquiventas2018`.`tventa` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muquiventas2018`.`pago_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muquiventas2018`.`pago_cliente` (
  `idpago_cliente` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cantidad` DECIMAL(18,2) NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idpago_cliente`),
  INDEX `fk_pago_cliente_cliente1_idx` (`cliente_idcliente` ASC),
  CONSTRAINT `fk_pago_cliente_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `muquiventas2018`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muquiventas2018`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muquiventas2018`.`departamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `muquiventas2018`.`tproducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muquiventas2018`.`tproducto` (
  `idProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `codigoBarras` VARCHAR(70) NOT NULL,
  `nombre` VARCHAR(700) NOT NULL,
  `precioVentaUnitario` DECIMAL(18,2) NOT NULL,
  `cantidad` DECIMAL(18,2) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `precioProveedor` DECIMAL(18,2) NOT NULL,
  `categoria_id` INT(11) NOT NULL,
  `precioMayoreo` DECIMAL(18,2) NULL,
  `comosevende` VARCHAR(45) NULL,
  `inventariar` TINYINT(1) NULL,
  `minimo` INT NULL,
  `IVA` DECIMAL(18,2) NULL,
  `IEPS` DECIMAL(18,2) NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `codigoBarras_UNIQUE` (`codigoBarras` ASC),
  INDEX `fk_TProducto_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_TProducto_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `muquiventas2018`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 174
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `muquiventas2018`.`Contenido_paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muquiventas2018`.`Contenido_paquete` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(18,2) NULL,
  `Precio_Unitario` DECIMAL(18,2) NULL,
  `tproducto_idProducto` INT(11) NOT NULL,
  `id_paquete` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Contenido_paquete_tproducto1_idx` (`tproducto_idProducto` ASC),
  CONSTRAINT `fk_Contenido_paquete_tproducto1`
    FOREIGN KEY (`tproducto_idProducto`)
    REFERENCES `muquiventas2018`.`tproducto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `muquiventas2018` ;

-- -----------------------------------------------------
-- Table `muquiventas2018`.`egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muquiventas2018`.`egreso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(18,2) NOT NULL,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  `usuario_id` INT(11) NOT NULL,
  `fecha_Movimiento` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Egreso_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Egreso_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `muquiventas2018`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 905
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `muquiventas2018`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muquiventas2018`.`ingreso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(18,2) NOT NULL,
  `descrpcion` VARCHAR(300) NULL DEFAULT NULL,
  `usuario_id` INT(11) NOT NULL,
  `fecha_Movimiento` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ingreso_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Ingreso_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `muquiventas2018`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3160
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `muquiventas2018`.`movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muquiventas2018`.`movimiento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `muquiventas2018`.`tventadetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muquiventas2018`.`tventadetalle` (
  `idVentaDetalle` INT(11) NOT NULL AUTO_INCREMENT,
  `idVenta` INT(11) NOT NULL,
  `idProducto` INT(11) NOT NULL,
  `codigoBarrasProducto` VARCHAR(70) NOT NULL,
  `nombreProducto` VARCHAR(700) NOT NULL,
  `precioVentaUnitarioProducto` DECIMAL(18,2) NOT NULL,
  `cantidad` DECIMAL(18,2) NOT NULL,
  `totalPrecioVenta` DECIMAL(18,2) NOT NULL,
  `precioProveedor` DECIMAL(18,2) NOT NULL,
  `IVA` DECIMAL(18,2) NULL,
  `IEPS` DECIMAL(18,2) NULL,
  `imprimir` TINYINT(1) NULL,
  `comosevende` VARCHAR(45) NULL,
  PRIMARY KEY (`idVentaDetalle`),
  INDEX `fk_TVentaDetalle_TProducto_idx` (`idProducto` ASC),
  INDEX `fk_TVentaDetalle_TVenta1_idx` (`idVenta` ASC),
  CONSTRAINT `fk_TVentaDetalle_TProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `muquiventas2018`.`tproducto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TVentaDetalle_TVenta1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `muquiventas2018`.`tventa` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16190
DEFAULT CHARACTER SET = utf8;

USE `muquiventas2018`;

DELIMITER $$
USE `muquiventas2018`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `muquiventas2018`.`trggBeforeInsertTVentaDetalle`
BEFORE INSERT ON `muquiventas2018`.`tventadetalle`
FOR EACH ROW
begin
set @cantidadAnterior=(select cantidad from TProducto where idProducto=New.idProducto);
update TProducto
set 
	cantidad=@cantidadAnterior-New.cantidad
where idProducto=New.idProducto;
end$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
