/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author mq12
 */
public class JpanelProductos extends javax.swing.JPanel {

    /**
     * Creates new form JpanelProductos
     */
    public JpanelProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPincipal = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonAlta = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonDepartamento = new javax.swing.JButton();

        jPanelPincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelPincipalLayout = new javax.swing.GroupLayout(jPanelPincipal);
        jPanelPincipal.setLayout(jPanelPincipalLayout);
        jPanelPincipalLayout.setHorizontalGroup(
            jPanelPincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelPincipalLayout.setVerticalGroup(
            jPanelPincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonAlta.setText("Alta");
        jButtonAlta.setFocusable(false);
        jButtonAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAlta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonAlta);

        jButtonModificar.setText("Modificar");
        jButtonModificar.setFocusable(false);
        jButtonModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonModificar);

        jButtonDepartamento.setText("Departamento");
        jButtonDepartamento.setFocusable(false);
        jButtonDepartamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDepartamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepartamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonDepartamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDepartamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAlta;
    public javax.swing.JButton jButtonDepartamento;
    public javax.swing.JButton jButtonModificar;
    public javax.swing.JPanel jPanelPincipal;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
