/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author mq12
 */
public class JpanelVentas extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    public JpanelVentas() {
      
        initComponents();
        jLabelMayoreio.setVisible(false);
        
//        jTableVender.getTableHeader().setReorderingAllowed(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigoBarras = new javax.swing.JTextField();
        jButtonAgregarProducto = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonInsertarMasD1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jButtonCobrar = new javax.swing.JButton();
        jTabbedPaneTickets = new javax.swing.JTabbedPane();
        jButtonCambiarTicket = new javax.swing.JButton();
        jButtonCrearTicket = new javax.swing.JButton();
        jButtonEliminarTicket = new javax.swing.JButton();
        jButtonMayoreo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelMayoreio = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setText("Codigo de barras");

        jTextFieldCodigoBarras.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jButtonAgregarProducto.setText("ENTER - Agregar Producto");

        jButtonBuscar.setText("F1 - Buscar");

        jButtonInsertarMasD1.setText("F2 - Insertar mas de 1 producto");

        jButton5.setText("suprimir - Borrar");

        jLabelTotal.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(23, 77, 244));
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotal.setText("$ 0");

        jButtonCobrar.setText("F12 - Cobrar");

        jTabbedPaneTickets.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jButtonCambiarTicket.setText("F6  - cambiar ticket");

        jButtonCrearTicket.setText("F5 -  crear ticket");

        jButtonEliminarTicket.setText("F7 - Eliminar ticket");

        jButtonMayoreo.setText("F3 - Mayoreo");

        jButton2.setText("F4 - Verificador");

        jLabelMayoreio.setBackground(new java.awt.Color(0, 0, 255));
        jLabelMayoreio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelMayoreio.setForeground(new java.awt.Color(255, 0, 51));
        jLabelMayoreio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMayoreio.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 387, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPaneTickets)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCrearTicket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCambiarTicket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEliminarTicket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInsertarMasD1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMayoreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelMayoreio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMayoreio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonInsertarMasD1)
                    .addComponent(jButton5)
                    .addComponent(jButtonMayoreo)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneTickets, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCrearTicket)
                            .addComponent(jButtonCambiarTicket)
                            .addComponent(jButtonEliminarTicket))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCobrar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    public javax.swing.JButton jButtonAgregarProducto;
    public javax.swing.JButton jButtonBuscar;
    public javax.swing.JButton jButtonCambiarTicket;
    public javax.swing.JButton jButtonCobrar;
    public javax.swing.JButton jButtonCrearTicket;
    public javax.swing.JButton jButtonEliminarTicket;
    public javax.swing.JButton jButtonInsertarMasD1;
    public javax.swing.JButton jButtonMayoreo;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabelMayoreio;
    public javax.swing.JLabel jLabelTotal;
    public javax.swing.JTabbedPane jTabbedPaneTickets;
    public javax.swing.JTextField jTextFieldCodigoBarras;
    // End of variables declaration//GEN-END:variables
}
