package modelo;
// Generated 21/12/2018 12:33:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContenidoPaquete generated by hbm2java
 */
@Entity
@Table(name="contenido_paquete"
    
)
public class ContenidoPaquete  implements java.io.Serializable {


     private Integer id;
     private Tproducto tproducto;
     private BigDecimal cantidad;
     private BigDecimal precioUnitario;
     private Integer idPaquete;

    public ContenidoPaquete() {
    }

	
    public ContenidoPaquete(Tproducto tproducto) {
        this.tproducto = tproducto;
    }
    public ContenidoPaquete(Tproducto tproducto, BigDecimal cantidad, BigDecimal precioUnitario, Integer idPaquete) {
       this.tproducto = tproducto;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.idPaquete = idPaquete;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tproducto_idProducto", nullable=false)
    public Tproducto getTproducto() {
        return this.tproducto;
    }
    
    public void setTproducto(Tproducto tproducto) {
        this.tproducto = tproducto;
    }

    
    @Column(name="cantidad", precision=18)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="Precio_Unitario", precision=18)
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }

    
    @Column(name="id_paquete")
    public Integer getIdPaquete() {
        return this.idPaquete;
    }
    
    public void setIdPaquete(Integer idPaquete) {
        this.idPaquete = idPaquete;
    }




}


