package modelo;
// Generated 21/12/2018 12:33:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
   
)
public class Departamento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Tproducto> tproductos = new HashSet<Tproducto>(0);

    public Departamento() {
    }

	
    public Departamento(String nombre) {
        this.nombre = nombre;
    }
    public Departamento(String nombre, Set<Tproducto> tproductos) {
       this.nombre = nombre;
       this.tproductos = tproductos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set<Tproducto> getTproductos() {
        return this.tproductos;
    }
    
    public void setTproductos(Set<Tproducto> tproductos) {
        this.tproductos = tproductos;
    }




}


