package modelo;
// Generated 21/12/2018 12:33:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Formadepago generated by hbm2java
 */
@Entity
@Table(name="formadepago"

)
public class Formadepago  implements java.io.Serializable {


     private Integer idPago;
     private Tventa tventa;
     private String tipo;
     private BigDecimal cantidad;
     private String referencia;

    public Formadepago() {
    }

	
    public Formadepago(Tventa tventa) {
        this.tventa = tventa;
    }
    public Formadepago(Tventa tventa, String tipo, BigDecimal cantidad, String referencia) {
       this.tventa = tventa;
       this.tipo = tipo;
       this.cantidad = cantidad;
       this.referencia = referencia;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPago", unique=true, nullable=false)
    public Integer getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tventa_idVenta", nullable=false)
    public Tventa getTventa() {
        return this.tventa;
    }
    
    public void setTventa(Tventa tventa) {
        this.tventa = tventa;
    }

    
    @Column(name="tipo", length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="cantidad", precision=18)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="referencia", length=45)
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }




}


