package modelo;
// Generated 21/12/2018 12:33:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ingreso generated by hbm2java
 */
@Entity
@Table(name="ingreso"
    
)
public class Ingreso  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private BigDecimal cantidad;
     private String descrpcion;
     private Date fechaMovimiento;
     private String nombre;
     private Date fecha;

    public Ingreso() {
    }

	
    public Ingreso(Usuario usuario, BigDecimal cantidad, Date fechaMovimiento, String nombre, Date fecha) {
        this.usuario = usuario;
        this.cantidad = cantidad;
        this.fechaMovimiento = fechaMovimiento;
        this.nombre = nombre;
        this.fecha = fecha;
    }
    public Ingreso(Usuario usuario, BigDecimal cantidad, String descrpcion, Date fechaMovimiento, String nombre, Date fecha) {
       this.usuario = usuario;
       this.cantidad = cantidad;
       this.descrpcion = descrpcion;
       this.fechaMovimiento = fechaMovimiento;
       this.nombre = nombre;
       this.fecha = fecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="cantidad", nullable=false, precision=18)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="descrpcion", length=300)
    public String getDescrpcion() {
        return this.descrpcion;
    }
    
    public void setDescrpcion(String descrpcion) {
        this.descrpcion = descrpcion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_Movimiento", nullable=false, length=19)
    public Date getFechaMovimiento() {
        return this.fechaMovimiento;
    }
    
    public void setFechaMovimiento(Date fechaMovimiento) {
        this.fechaMovimiento = fechaMovimiento;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


