package modelo;
// Generated 21/12/2018 12:33:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    
    , uniqueConstraints = @UniqueConstraint(columnNames="nombre") 
)
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private int nivel;
     private String nombre;
     private String password;
     private Set<Egreso> egresos = new HashSet<Egreso>(0);
     private Set<Tventa> tventas = new HashSet<Tventa>(0);
     private Set<Ingreso> ingresos = new HashSet<Ingreso>(0);

    public Usuario() {
    }

	
    public Usuario(int nivel, String nombre, String password) {
        this.nivel = nivel;
        this.nombre = nombre;
        this.password = password;
    }
    public Usuario(int nivel, String nombre, String password, Set<Egreso> egresos, Set<Tventa> tventas, Set<Ingreso> ingresos) {
       this.nivel = nivel;
       this.nombre = nombre;
       this.password = password;
       this.egresos = egresos;
       this.tventas = tventas;
       this.ingresos = ingresos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nivel", nullable=false)
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="nombre", unique=true, nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Egreso> getEgresos() {
        return this.egresos;
    }
    
    public void setEgresos(Set<Egreso> egresos) {
        this.egresos = egresos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Tventa> getTventas() {
        return this.tventas;
    }
    
    public void setTventas(Set<Tventa> tventas) {
        this.tventas = tventas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Ingreso> getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set<Ingreso> ingresos) {
        this.ingresos = ingresos;
    }




}


