/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.producto;

/**
 *
 * @author mq12
 */
public class JpanelContenidoPaquete extends javax.swing.JPanel {

    /**
     * Creates new form JpanelContenidoPaquete
     */
    public JpanelContenidoPaquete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContenido = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPaqueteCodigo = new javax.swing.JTextField();
        jButtonPaqueteAceptar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldPaqueteNombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPaquetePrecioCosto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldPaqueteCantidad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldPaquetePrecioVenta = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonPaqueteAgregar = new javax.swing.JButton();
        jLabelErrorCantidadPaquete = new javax.swing.JLabel();
        jLabelErrorPrecioPaquete = new javax.swing.JLabel();

        jButtonGuardar.setText("Guardar");

        jTableContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cantidad", "Precio venta", "Precion costo"
            }
        ));
        jScrollPane1.setViewportView(jTableContenido);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Contenido del paquete");

        jLabel13.setText("Codigo");

        jButtonPaqueteAceptar.setText("Aceptar");

        jLabel16.setText("Nombre");

        jTextFieldPaqueteNombre.setEditable(false);

        jLabel14.setText("Precio Costo");

        jTextFieldPaquetePrecioCosto.setEditable(false);

        jLabel17.setText("Cantidad");

        jLabel15.setText("Precio Venta por unidad");

        jButtonLimpiar.setText("Limpiar");

        jButtonPaqueteAgregar.setText("Agregar");

        jLabelErrorCantidadPaquete.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabelErrorCantidadPaquete.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorCantidadPaquete.setText("Error");

        jLabelErrorPrecioPaquete.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabelErrorPrecioPaquete.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorPrecioPaquete.setText("Error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonGuardar))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPaqueteNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPaqueteCodigo)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPaquetePrecioCosto)
                                    .addComponent(jTextFieldPaqueteCantidad)
                                    .addComponent(jTextFieldPaquetePrecioVenta))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelErrorCantidadPaquete)
                                    .addComponent(jButtonPaqueteAceptar)
                                    .addComponent(jLabelErrorPrecioPaquete))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonLimpiar)
                                .addGap(18, 18, 18)))
                        .addComponent(jButtonPaqueteAgregar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldPaqueteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPaqueteAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldPaqueteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldPaquetePrecioCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextFieldPaqueteCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorCantidadPaquete))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldPaquetePrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorPrecioPaquete))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPaqueteAgregar)
                            .addComponent(jButtonLimpiar))
                        .addGap(9, 9, 9)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jButtonGuardar))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonGuardar;
    public javax.swing.JButton jButtonLimpiar;
    public javax.swing.JButton jButtonPaqueteAceptar;
    public javax.swing.JButton jButtonPaqueteAgregar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabelErrorCantidadPaquete;
    public javax.swing.JLabel jLabelErrorPrecioPaquete;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableContenido;
    public javax.swing.JTextField jTextFieldPaqueteCantidad;
    public javax.swing.JTextField jTextFieldPaqueteCodigo;
    public javax.swing.JTextField jTextFieldPaqueteNombre;
    public javax.swing.JTextField jTextFieldPaquetePrecioCosto;
    public javax.swing.JTextField jTextFieldPaquetePrecioVenta;
    // End of variables declaration//GEN-END:variables
}
