/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.producto;

import validar.ValidarEntradas;

/**
 *
 * @author mq12
 */
public class JpanelProductoModificar extends javax.swing.JPanel {

    /**
     * Creates new form jpanelNuevo
     */
    public JpanelProductoModificar() {
        initComponents();
        
        new ValidarEntradas().moneda(jTextFieldPrecioCosto);
           new ValidarEntradas().moneda(jTextFieldPrecioMayoreo);
              new ValidarEntradas().moneda(jTextFieldPrecioMenudeo);
              
                 new ValidarEntradas().moneda(jTextFieldGanacia);
                 new ValidarEntradas().moneda(jTextFieldCantidadInventario);
                 new ValidarEntradas().moneda(jTextFieldMinimoInventario);
                 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSeVende = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCodigoBarras = new javax.swing.JTextField();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldPrecioCosto = new javax.swing.JTextField();
        jRadioButtonUnidad = new javax.swing.JRadioButton();
        jRadioButtonGranel = new javax.swing.JRadioButton();
        jRadioButtonPaquete = new javax.swing.JRadioButton();
        jTextFieldGanacia = new javax.swing.JTextField();
        jTextFieldPrecioMenudeo = new javax.swing.JTextField();
        jTextFieldPrecioMayoreo = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jCheckBoxInventario = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCantidadInventario = new javax.swing.JTextField();
        jTextFieldMinimoInventario = new javax.swing.JTextField();
        jComboBoxDepartamento = new javax.swing.JComboBox<>();
        jLabel1ErrorDescripcion = new javax.swing.JLabel();
        jLabel1ErrorCodigoBarras = new javax.swing.JLabel();
        jLabel1ErrorCosto = new javax.swing.JLabel();
        jLabel14ErrorPrecioventa = new javax.swing.JLabel();
        jLabelErrorPrecioMayoreo = new javax.swing.JLabel();
        jLabelErrorCantidad = new javax.swing.JLabel();
        jLabel1ErrorMinimo = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldCaptureCodigoBarras = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxMovimiento = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setText("Modificar Producto");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Codigo de barras");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Descripción");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Como se vende");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Precio Costo");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Ganancia");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Precio Venta");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Precio Mayoreo");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Departamento");

        jTextFieldCodigoBarras.setEditable(false);
        jTextFieldCodigoBarras.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTextFieldDescripcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTextFieldPrecioCosto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        buttonGroupSeVende.add(jRadioButtonUnidad);
        jRadioButtonUnidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButtonUnidad.setSelected(true);
        jRadioButtonUnidad.setText("Unidad/pieza");

        buttonGroupSeVende.add(jRadioButtonGranel);
        jRadioButtonGranel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButtonGranel.setText("A granel");

        buttonGroupSeVende.add(jRadioButtonPaquete);
        jRadioButtonPaquete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButtonPaquete.setText("Paquete");

        jTextFieldGanacia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTextFieldPrecioMenudeo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTextFieldPrecioMayoreo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jButtonGuardar.setText("Guardar");

        jCheckBoxInventario.setSelected(true);
        jCheckBoxInventario.setText("Usar Inventario");

        jLabel10.setText("Cantidad");

        jLabel11.setText("Minimo");

        jComboBoxDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin departamento" }));

        jLabel1ErrorDescripcion.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel1ErrorDescripcion.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1ErrorDescripcion.setText("Error");

        jLabel1ErrorCodigoBarras.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel1ErrorCodigoBarras.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1ErrorCodigoBarras.setText("Error");

        jLabel1ErrorCosto.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel1ErrorCosto.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1ErrorCosto.setText("Error");

        jLabel14ErrorPrecioventa.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel14ErrorPrecioventa.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14ErrorPrecioventa.setText("Error");

        jLabelErrorPrecioMayoreo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabelErrorPrecioMayoreo.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorPrecioMayoreo.setText("Error");

        jLabelErrorCantidad.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabelErrorCantidad.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorCantidad.setText("Error");

        jLabel1ErrorMinimo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel1ErrorMinimo.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1ErrorMinimo.setText("Error");

        jButtonBuscar.setText("Buscar Producto");
        jButtonBuscar.setPreferredSize(new java.awt.Dimension(111, 26));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Capture Codigo");

        jComboBoxMovimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxMovimiento.setForeground(new java.awt.Color(255, 0, 51));
        jComboBoxMovimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Añadir Productos", "Modificar precio Proveedor", "Modificar Cantidad" }));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Movimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(337, 337, 337))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPrecioMayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelErrorPrecioMayoreo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jCheckBoxInventario)
                                            .addComponent(jTextFieldCantidadInventario)
                                            .addComponent(jTextFieldMinimoInventario)
                                            .addComponent(jComboBoxDepartamento, 0, 200, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelErrorCantidad)
                                            .addComponent(jLabel1ErrorMinimo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldPrecioCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1ErrorCosto))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButtonUnidad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButtonGranel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButtonPaquete))
                                            .addComponent(jTextFieldGanacia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldPrecioMenudeo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14ErrorPrecioventa)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel1ErrorCodigoBarras))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel1ErrorDescripcion))))
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(18, 18, 18)
                                            .addComponent(jComboBoxMovimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(14, 14, 14)
                                                    .addComponent(jTextFieldCaptureCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonGuardar)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCaptureCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1ErrorCodigoBarras)
                        .addComponent(jTextFieldCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1ErrorDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonUnidad)
                    .addComponent(jRadioButtonGranel)
                    .addComponent(jRadioButtonPaquete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1ErrorCosto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPrecioCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldGanacia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14ErrorPrecioventa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPrecioMenudeo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPrecioMayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorPrecioMayoreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCantidadInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldMinimoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1ErrorMinimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButtonGuardar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupSeVende;
    public javax.swing.JButton jButtonBuscar;
    public javax.swing.JButton jButtonGuardar;
    public javax.swing.JCheckBox jCheckBoxInventario;
    public javax.swing.JComboBox<String> jComboBoxDepartamento;
    public javax.swing.JComboBox<String> jComboBoxMovimiento;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14ErrorPrecioventa;
    public javax.swing.JLabel jLabel1ErrorCodigoBarras;
    public javax.swing.JLabel jLabel1ErrorCosto;
    public javax.swing.JLabel jLabel1ErrorDescripcion;
    public javax.swing.JLabel jLabel1ErrorMinimo;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelErrorCantidad;
    public javax.swing.JLabel jLabelErrorPrecioMayoreo;
    public javax.swing.JRadioButton jRadioButtonGranel;
    public javax.swing.JRadioButton jRadioButtonPaquete;
    public javax.swing.JRadioButton jRadioButtonUnidad;
    public javax.swing.JTextField jTextFieldCantidadInventario;
    public javax.swing.JTextField jTextFieldCaptureCodigoBarras;
    public javax.swing.JTextField jTextFieldCodigoBarras;
    public javax.swing.JTextField jTextFieldDescripcion;
    public javax.swing.JTextField jTextFieldGanacia;
    public javax.swing.JTextField jTextFieldMinimoInventario;
    public javax.swing.JTextField jTextFieldPrecioCosto;
    public javax.swing.JTextField jTextFieldPrecioMayoreo;
    public javax.swing.JTextField jTextFieldPrecioMenudeo;
    // End of variables declaration//GEN-END:variables
}
